# Imports

In [1]:
import os
import pandas as pd
from huggingface_hub import login

import timm
from PIL import Image

import torch
from torchvision import transforms
from gigapath.pipeline import tile_one_slide, load_tile_slide_encoder, run_inference_with_tile_encoder, run_inference_with_slide_encoder

torch.cuda.empty_cache()

/home/ge26xaj/miniconda3/envs/gigapath/lib/python3.9/site-packages/timm/models/registry.py:4: FutureWarning: Importing from timm.models.registry is deprecated, please import via timm.models
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.models", FutureWarning)
/home/ge26xaj/miniconda3/envs/gigapath/lib/python3.9/site-packages/timm/models/layers/__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)

# Login to Huggingface

In [3]:
login("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")
!export HF_TOKEN="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"

Token will not been saved to git credential helper. Pass `add_to_git_credential=True` if you want to set the git credential as well.
Token is valid (permission: read).
Your token has been saved to /home/ge26xaj/.cache/huggingface/token
Login successful

# Create Encoders

In [4]:
# Older versions of timm have compatibility issues. Please ensure that you use a newer version by running the following command: pip install timm>=1.0.3.
tile_encoder = timm.create_model("hf_hub:prov-gigapath/prov-gigapath", pretrained=True)

transform = transforms.Compose(
    [
        transforms.Resize(256, interpolation=transforms.InterpolationMode.BICUBIC),
        transforms.CenterCrop(224),
        transforms.ToTensor(),
        transforms.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225)),
    ]
)

/home/ge26xaj/miniconda3/envs/gigapath/lib/python3.9/site-packages/torch/_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()

In [5]:
# Load the tile and slide encoder models
# NOTE: The CLS token is not trained during the slide-level pretraining.
# Here, we enable the use of global pooling for the output embeddings.
tile_encoder, slide_encoder_model = load_tile_slide_encoder(global_pool=True)

Tile encoder param # 1134953984
dilated_ratio:  [1, 2, 4, 8, 16]
segment_length:  [1024, 5792, 32768, 185363, 1048576]
Number of trainable LongNet parameters:  85148160
Global Pooling: True

slide_encoder.pth:   0%|          | 0.00/345M [00:00<?, ?B/s]

 Successfully Loaded Pretrained GigaPath model from hf_hub:prov-gigapath/prov-gigapath
Slide encoder param # 86330880

# Create Tiles from Slide

In [ ]:
# assert "HF_TOKEN" in os.environ, "Please set the HF_TOKEN environment variable to your Hugging Face API token"
img_path = "../../../../../../../../mnt/data/Dataset/CAMELYON16/images/normal_041.tif"

# local_dir = os.path.join(os.path.expanduser("~"), ".cache/")
# huggingface_hub.hf_hub_download("prov-gigapath/prov-gigapath", filename="sample_data/PROV-000-000001.ndpi", local_dir=local_dir, force_download=True)
slide_path = os.path.join(img_path)

save_dir = os.path.join('outputs/preprocessing/')

print("NOTE: Prov-GigaPath is trained with 0.5 mpp preprocessed slides. Please make sure to use the appropriate level for the 0.5 MPP")
tile_one_slide(slide_path, save_dir=save_dir, level=1)

print("NOTE: tiling dependency libraries can be tricky to set up. Please double check the generated tile images.")

In [11]:
# load image tiles
slide_dir = "outputs/preprocessing/output/" + os.path.basename(slide_path) + "/"
image_paths = [os.path.join(slide_dir, img) for img in os.listdir(slide_dir) if img.endswith('.png')]

print(f"Found {len(image_paths)} image tiles")

Found 7258 image tiles

# Encode Tiles

In [6]:
tile_path = "./outputs/preprocessing/output/normal_040.tif/20480x_124928y.png"

sample_input = transform(Image.open(tile_path).convert("RGB")).unsqueeze(0)

tile_encoder.eval()
with torch.no_grad():
    output = tile_encoder(sample_input).squeeze()

In [7]:
torch.cuda.current_device()
torch.cuda.get_device_name(0)

'NVIDIA GeForce RTX 3090'

In [12]:
tile_encoder_outputs = run_inference_with_tile_encoder(image_paths, tile_encoder)

for k in tile_encoder_outputs.keys():
    print(f"tile_encoder_outputs[{k}].shape: {tile_encoder_outputs[k].shape}")

Running inference with tile encoder: 100%|██████████| 57/57 [01:25<00:00,  1.50s/it]

tile_encoder_outputs[tile_embeds].shape: torch.Size([7258, 1536])
tile_encoder_outputs[coords].shape: torch.Size([7258, 2])

# Encode Slides

In [13]:
# run inference with the slide encoder
slide_embeds = run_inference_with_slide_encoder(slide_encoder_model=slide_encoder_model, **tile_encoder_outputs)
print(slide_embeds.keys())

dict_keys(['layer_0_embed', 'layer_1_embed', 'layer_2_embed', 'layer_3_embed', 'layer_4_embed', 'layer_5_embed', 'layer_6_embed', 'layer_7_embed', 'layer_8_embed', 'layer_9_embed', 'layer_10_embed', 'layer_11_embed', 'layer_12_embed', 'last_layer_embed'])

In [14]:
print((slide_embeds["last_layer_embed"]).shape)

torch.Size([1, 768])

In [2]:
import pandas as pd

df = pd.read_excel("../../../../../../../../mnt/nfs03-R6/BRACS/BRACS.xlsx")
slides = df['WSI Filename']
len(slides)
df

      WSI Filename  Patient Id  RoI  WSI label         Set
0        BRACS_264          85    24        PB     Testing
1        BRACS_265          87    18       UDH  Validation
2        BRACS_280          30    19        IC    Training
3        BRACS_281         111    37        IC    Training
4        BRACS_283         109    49        IC    Training
..             ...         ...   ...       ...         ...
542  BRACS_1003728          71     1       ADH    Training
543  BRACS_1003730         176     1        PB    Training
544  BRACS_1003731         153     1        IC    Training
545  BRACS_1003732         153     1        IC    Training
546  BRACS_1003734         166     1        PB    Training

[547 rows x 5 columns]

In [3]:
df[df["WSI Filename"]=="BRACS_1879"]

    WSI Filename  Patient Id  RoI  WSI label       Set
335   BRACS_1879         129     5        PB  Training

In [6]:
import os
from collections import defaultdict

# Specify the top-level directory
top_dir = "../../../../../../../../mnt/nfs03-R6/BRACS/BRACS_WSI//"

# Dictionary to store the counts for each folder
folder_counts = defaultdict(int)

# List to store all .svs file paths
svs_files = []

# Traverse the directory tree
for root, dirs, files in os.walk(top_dir):
    # Filter .svs files
    svs_in_folder = [file for file in files if file.lower().endswith(".svs")]
    
    # Count the .svs files in the current folder
    folder_counts[root] += len(svs_in_folder)
    
    # Append the full paths of the .svs files
    svs_files.extend([os.path.join(root, file) for file in svs_in_folder])

# Print the count of .svs files in each folder
print(len(svs_files))
print("\n.svs file counts per folder:")
for folder, count in folder_counts.items():
    if count > 0:
        print(f"{folder}: {count} files")

file_names = [os.path.basename(str(item)[:-4]) for item in svs_files]
# x =svs_files[0].split("/")[-1] #190
# x_split = x.split("_")
# x = f"{x_split[-2]}_{x_split[-1][:-3]}"
# df = pd.read_excel("../../../../../../mnt/nfs03-R6/BRACS/BRACS.xlsx")
# print(x)
# df[df["WSI Filename"]==x]
#547

546

.svs file counts per folder:
../../../../../../../../mnt/nfs03-R6/BRACS/BRACS_WSI//train/Group_MT/Type_DCIS: 40 files
../../../../../../../../mnt/nfs03-R6/BRACS/BRACS_WSI//train/Group_MT/Type_IC: 100 files
../../../../../../../../mnt/nfs03-R6/BRACS/BRACS_WSI//train/Group_AT/Type_FEA: 24 files
../../../../../../../../mnt/nfs03-R6/BRACS/BRACS_WSI//train/Group_AT/Type_ADH: 28 files
../../../../../../../../mnt/nfs03-R6/BRACS/BRACS_WSI//train/Group_BT/Type_N: 27 files
../../../../../../../../mnt/nfs03-R6/BRACS/BRACS_WSI//train/Group_BT/Type_PB: 120 files
../../../../../../../../mnt/nfs03-R6/BRACS/BRACS_WSI//train/Group_BT/Type_UDH: 55 files
../../../../../../../../mnt/nfs03-R6/BRACS/BRACS_WSI//val/Group_MT/Type_DCIS: 9 files
../../../../../../../../mnt/nfs03-R6/BRACS/BRACS_WSI//val/Group_MT/Type_IC: 12 files
../../../../../../../../mnt/nfs03-R6/BRACS/BRACS_WSI//val/Group_AT/Type_FEA: 6 files
../../../../../../../../mnt/nfs03-R6/BRACS/BRACS_WSI//val/Group_AT/Type_ADH: 8 files
../../../../../../../../mnt/nfs03-R6/BRACS/BRACS_WSI//val/Group_BT/Type_N: 10 files
../../../../../../../../mnt/nfs03-R6/BRACS/BRACS_WSI//val/Group_BT/Type_PB: 11 files
../../../../../../../../mnt/nfs03-R6/BRACS/BRACS_WSI//val/Group_BT/Type_UDH: 9 files
../../../../../../../../mnt/nfs03-R6/BRACS/BRACS_WSI//test/Group_MT/Type_DCIS: 12 files
../../../../../../../../mnt/nfs03-R6/BRACS/BRACS_WSI//test/Group_MT/Type_IC: 20 files
../../../../../../../../mnt/nfs03-R6/BRACS/BRACS_WSI//test/Group_AT/Type_FEA: 11 files
../../../../../../../../mnt/nfs03-R6/BRACS/BRACS_WSI//test/Group_AT/Type_ADH: 12 files
../../../../../../../../mnt/nfs03-R6/BRACS/BRACS_WSI//test/Group_BT/Type_N: 7 files
../../../../../../../../mnt/nfs03-R6/BRACS/BRACS_WSI//test/Group_BT/Type_PB: 16 files
../../../../../../../../mnt/nfs03-R6/BRACS/BRACS_WSI//test/Group_BT/Type_UDH: 9 files

In [23]:
pd.read_csv("../../fm_histopathology/scripts/CLAM/presets/tcga.csv")

,seg_level,sthresh,mthresh,close,use_otsu,a_t,a_h,max_n_holes,vis_level,line_thickness,white_thresh,black_thresh,use_padding,contour_fn,keep_ids,exclude_ids
0,-1,8,7,4,False,16,4,8,-1,100,5,50,True,four_pt,none,none

In [14]:
missing = []
for slide in slides:
    if slide not in file_names:
        missing.append(slide)

print(len(missing))
print(missing)

547
['BRACS_264', 'BRACS_265', 'BRACS_280', 'BRACS_281', 'BRACS_283', 'BRACS_286', 'BRACS_288', 'BRACS_291', 'BRACS_292', 'BRACS_295', 'BRACS_297', 'BRACS_298', 'BRACS_300', 'BRACS_301', 'BRACS_305', 'BRACS_310', 'BRACS_311', 'BRACS_734', 'BRACS_735', 'BRACS_736', 'BRACS_737', 'BRACS_738', 'BRACS_739', 'BRACS_740', 'BRACS_743', 'BRACS_745', 'BRACS_747', 'BRACS_748', 'BRACS_749', 'BRACS_750', 'BRACS_752', 'BRACS_753', 'BRACS_754', 'BRACS_755', 'BRACS_756', 'BRACS_757', 'BRACS_758', 'BRACS_759', 'BRACS_760', 'BRACS_761', 'BRACS_762', 'BRACS_773', 'BRACS_1228', 'BRACS_1231', 'BRACS_1232', 'BRACS_1233', 'BRACS_1235', 'BRACS_1238', 'BRACS_1239', 'BRACS_1240', 'BRACS_1241', 'BRACS_1242', 'BRACS_1244', 'BRACS_1247', 'BRACS_1248', 'BRACS_1249', 'BRACS_1250', 'BRACS_1251', 'BRACS_1253', 'BRACS_1255', 'BRACS_1257', 'BRACS_1259', 'BRACS_1261', 'BRACS_1263', 'BRACS_1265', 'BRACS_1267', 'BRACS_1269', 'BRACS_1270', 'BRACS_1271', 'BRACS_1272', 'BRACS_1273', 'BRACS_1274', 'BRACS_1275', 'BRACS_1276', 'BRACS_1277', 'BRACS_1279', 'BRACS_1283', 'BRACS_1284', 'BRACS_1286', 'BRACS_1287', 'BRACS_1288', 'BRACS_1289', 'BRACS_1292', 'BRACS_1293', 'BRACS_1295', 'BRACS_1296', 'BRACS_1318', 'BRACS_1319', 'BRACS_1320', 'BRACS_1321', 'BRACS_1322', 'BRACS_1324', 'BRACS_1325', 'BRACS_1326', 'BRACS_1327', 'BRACS_1329', 'BRACS_1330', 'BRACS_1334', 'BRACS_1335', 'BRACS_1336', 'BRACS_1337', 'BRACS_1338', 'BRACS_1356', 'BRACS_1357', 'BRACS_1358', 'BRACS_1360', 'BRACS_1361', 'BRACS_1362', 'BRACS_1366', 'BRACS_1367', 'BRACS_1368', 'BRACS_1369', 'BRACS_1370', 'BRACS_1374', 'BRACS_1378', 'BRACS_1379', 'BRACS_1385', 'BRACS_1386', 'BRACS_1392', 'BRACS_1393', 'BRACS_1394', 'BRACS_1395', 'BRACS_1401', 'BRACS_1403', 'BRACS_1404', 'BRACS_1405', 'BRACS_1406', 'BRACS_1407', 'BRACS_1408', 'BRACS_1409', 'BRACS_1411', 'BRACS_1412', 'BRACS_1413', 'BRACS_1414', 'BRACS_1416', 'BRACS_1423', 'BRACS_1424', 'BRACS_1473', 'BRACS_1474', 'BRACS_1476', 'BRACS_1477', 'BRACS_1478', 'BRACS_1480', 'BRACS_1483', 'BRACS_1484', 'BRACS_1485', 'BRACS_1486', 'BRACS_1487', 'BRACS_1489', 'BRACS_1490', 'BRACS_1491', 'BRACS_1492', 'BRACS_1493', 'BRACS_1494', 'BRACS_1495', 'BRACS_1496', 'BRACS_1497', 'BRACS_1498', 'BRACS_1499', 'BRACS_1503', 'BRACS_1506', 'BRACS_1507', 'BRACS_1508', 'BRACS_1509', 'BRACS_1510', 'BRACS_1511', 'BRACS_1512', 'BRACS_1513', 'BRACS_1514', 'BRACS_1515', 'BRACS_1516', 'BRACS_1578', 'BRACS_1579', 'BRACS_1580', 'BRACS_1581', 'BRACS_1582', 'BRACS_1583', 'BRACS_1584', 'BRACS_1585', 'BRACS_1587', 'BRACS_1588', 'BRACS_1589', 'BRACS_1590', 'BRACS_1591', 'BRACS_1592', 'BRACS_1593', 'BRACS_1594', 'BRACS_1595', 'BRACS_1596', 'BRACS_1597', 'BRACS_1598', 'BRACS_1599', 'BRACS_1601', 'BRACS_1602', 'BRACS_1603', 'BRACS_1604', 'BRACS_1605', 'BRACS_1606', 'BRACS_1607', 'BRACS_1608', 'BRACS_1609', 'BRACS_1610', 'BRACS_1612', 'BRACS_1614', 'BRACS_1616', 'BRACS_1617', 'BRACS_1618', 'BRACS_1619', 'BRACS_1620', 'BRACS_1621', 'BRACS_1622', 'BRACS_1631', 'BRACS_1632', 'BRACS_1633', 'BRACS_1634', 'BRACS_1635', 'BRACS_1636', 'BRACS_1637', 'BRACS_1638', 'BRACS_1639', 'BRACS_1640', 'BRACS_1641', 'BRACS_1642', 'BRACS_1643', 'BRACS_1645', 'BRACS_1646', 'BRACS_1647', 'BRACS_1648', 'BRACS_1649', 'BRACS_1650', 'BRACS_1652', 'BRACS_1653', 'BRACS_1654', 'BRACS_1655', 'BRACS_1656', 'BRACS_1658', 'BRACS_1659', 'BRACS_1660', 'BRACS_1661', 'BRACS_1664', 'BRACS_1665', 'BRACS_1666', 'BRACS_1667', 'BRACS_1668', 'BRACS_1669', 'BRACS_1771', 'BRACS_1772', 'BRACS_1773', 'BRACS_1774', 'BRACS_1775', 'BRACS_1777', 'BRACS_1778', 'BRACS_1779', 'BRACS_1780', 'BRACS_1782', 'BRACS_1783', 'BRACS_1784', 'BRACS_1785', 'BRACS_1786', 'BRACS_1787', 'BRACS_1788', 'BRACS_1789', 'BRACS_1791', 'BRACS_1792', 'BRACS_1793', 'BRACS_1794', 'BRACS_1795', 'BRACS_1796', 'BRACS_1797', 'BRACS_1798', 'BRACS_1799', 'BRACS_1808', 'BRACS_1810', 'BRACS_1811', 'BRACS_1812', 'BRACS_1813', 'BRACS_1814', 'BRACS_1815', 'BRACS_1816', 'BRACS_1817', 'BRACS_1820', 'BRACS_1821', 'BRACS_1823', 'BRACS_1824', 'BRACS_1825', 'BRACS_1826', 'BRACS_1827', 'BRACS_1828', 'BRACS_1829', 'BRACS_1830', 'BRACS_1831', 'BRACS_1832', 'BRACS_1833', 'BRACS_1834', 'BRACS_1835', 'BRACS_1836', 'BRACS_1837', 'BRACS_1838', 'BRACS_1839', 'BRACS_1840', 'BRACS_1841', 'BRACS_1842', 'BRACS_1843', 'BRACS_1844', 'BRACS_1845', 'BRACS_1846', 'BRACS_1847', 'BRACS_1848', 'BRACS_1849', 'BRACS_1850', 'BRACS_1851', 'BRACS_1852', 'BRACS_1853', 'BRACS_1855', 'BRACS_1856', 'BRACS_1857', 'BRACS_1858', 'BRACS_1860', 'BRACS_1861', 'BRACS_1862', 'BRACS_1863', 'BRACS_1864', 'BRACS_1865', 'BRACS_1866', 'BRACS_1867', 'BRACS_1869', 'BRACS_1870', 'BRACS_1871', 'BRACS_1872', 'BRACS_1873', 'BRACS_1874', 'BRACS_1875', 'BRACS_1876', 'BRACS_1877', 'BRACS_1878', 'BRACS_1879', 'BRACS_1880', 'BRACS_1881', 'BRACS_1882', 'BRACS_1883', 'BRACS_1885', 'BRACS_1886', 'BRACS_1888', 'BRACS_1890', 'BRACS_1892', 'BRACS_1893', 'BRACS_1895', 'BRACS_1896', 'BRACS_1897', 'BRACS_1899', 'BRACS_1900', 'BRACS_1901', 'BRACS_1902', 'BRACS_1903', 'BRACS_1904', 'BRACS_1905', 'BRACS_1906', 'BRACS_1908', 'BRACS_1910', 'BRACS_1911', 'BRACS_1912', 'BRACS_1913', 'BRACS_1914', 'BRACS_1915', 'BRACS_1916', 'BRACS_1917', 'BRACS_1918', 'BRACS_1919', 'BRACS_1920', 'BRACS_1921', 'BRACS_1922', 'BRACS_1923', 'BRACS_1924', 'BRACS_1925', 'BRACS_1926', 'BRACS_1927', 'BRACS_1928', 'BRACS_1929', 'BRACS_1930', 'BRACS_1931', 'BRACS_1932', 'BRACS_1933', 'BRACS_1934', 'BRACS_1935', 'BRACS_1936', 'BRACS_1937', 'BRACS_1938', 'BRACS_1940', 'BRACS_1941', 'BRACS_1942', 'BRACS_1943', 'BRACS_1944', 'BRACS_1945', 'BRACS_1946', 'BRACS_1947', 'BRACS_1948', 'BRACS_1949', 'BRACS_1950', 'BRACS_1952', 'BRACS_1953', 'BRACS_1954', 'BRACS_1955', 'BRACS_1957', 'BRACS_1958', 'BRACS_1959', 'BRACS_1960', 'BRACS_1961', 'BRACS_1962', 'BRACS_1963', 'BRACS_1964', 'BRACS_1965', 'BRACS_1966', 'BRACS_1967', 'BRACS_1968', 'BRACS_1969', 'BRACS_1970', 'BRACS_1971', 'BRACS_1972', 'BRACS_1973', 'BRACS_1974', 'BRACS_1975', 'BRACS_1977', 'BRACS_1978', 'BRACS_1979', 'BRACS_1980', 'BRACS_1981', 'BRACS_1982', 'BRACS_1983', 'BRACS_1984', 'BRACS_1986', 'BRACS_1987', 'BRACS_1988', 'BRACS_1989', 'BRACS_1993', 'BRACS_1994', 'BRACS_1995', 'BRACS_1996', 'BRACS_1997', 'BRACS_1998', 'BRACS_1999', 'BRACS_2000', 'BRACS_2001', 'BRACS_2002', 'BRACS_2004', 'BRACS_2005', 'BRACS_2007', 'BRACS_3266', 'BRACS_3268', 'BRACS_3269', 'BRACS_3270', 'BRACS_3271', 'BRACS_3272', 'BRACS_3273', 'BRACS_3274', 'BRACS_3275', 'BRACS_3276', 'BRACS_3277', 'BRACS_3278', 'BRACS_3279', 'BRACS_3281', 'BRACS_3282', 'BRACS_3283', 'BRACS_3284', 'BRACS_3285', 'BRACS_3289', 'BRACS_3290', 'BRACS_3291', 'BRACS_3292', 'BRACS_3293', 'BRACS_3294', 'BRACS_3295', 'BRACS_3296', 'BRACS_3298', 'BRACS_3300', 'BRACS_3301', 'BRACS_3302', 'BRACS_3305', 'BRACS_3308', 'BRACS_3309', 'BRACS_3310', 'BRACS_3311', 'BRACS_3312', 'BRACS_3313', 'BRACS_3314', 'BRACS_3315', 'BRACS_3316', 'BRACS_3317', 'BRACS_3318', 'BRACS_3319', 'BRACS_3320', 'BRACS_3321', 'BRACS_3322', 'BRACS_3323', 'BRACS_3324', 'BRACS_3334', 'BRACS_3335', 'BRACS_3336', 'BRACS_3337', 'BRACS_1003658', 'BRACS_1003659', 'BRACS_1003660', 'BRACS_1003661', 'BRACS_1003667', 'BRACS_1003668', 'BRACS_1003669', 'BRACS_1003670', 'BRACS_1003671', 'BRACS_1003672', 'BRACS_1003673', 'BRACS_1003675', 'BRACS_1003677', 'BRACS_1003678', 'BRACS_1003684', 'BRACS_1003685', 'BRACS_1003686', 'BRACS_1003691', 'BRACS_1003692', 'BRACS_1003693', 'BRACS_1003694', 'BRACS_1003697', 'BRACS_1003698', 'BRACS_1003699', 'BRACS_1003700', 'BRACS_1003703', 'BRACS_1003705', 'BRACS_1003706', 'BRACS_1003707', 'BRACS_1003708', 'BRACS_1003709', 'BRACS_1003710', 'BRACS_1003713', 'BRACS_1003714', 'BRACS_1003715', 'BRACS_1003716', 'BRACS_1003717', 'BRACS_1003718', 'BRACS_1003721', 'BRACS_1003722', 'BRACS_1003723', 'BRACS_1003724', 'BRACS_1003725', 'BRACS_1003727', 'BRACS_1003728', 'BRACS_1003730', 'BRACS_1003731', 'BRACS_1003732', 'BRACS_1003734']

In [5]:
torch.load("../../../../../../../../mnt/nfs03-R6/CAMELYON16/slides_cls/feats_UNI/pt_files/normal_009.pth").shape

torch.Size([1976, 1024])

In [5]:
# tiles: 217

cmd:
python create_tiles.py --images-dir ../../../../../../../../mnt/nfs03-R6/BRACS/BRACS_WSI/train/Group_AT/Type_FEA --save-dir ../../../../../../../../mnt/nfs03-R6/BRACS/gigapath_tiles/train/Group_AT/Type_FEA

Done:
../../../../../../../../mnt/nfs03-R6/BRACS/BRACS_WSI/train/Group_MT/Type_DCIS: 40 files
../../../../../../../../mnt/nfs03-R6/BRACS/BRACS_WSI/train/Group_MT/Type_IC: 100 files
../../../../../../../../mnt/nfs03-R6/BRACS/BRACS_WSI/train/Group_AT/Type_FEA: 24 files
../../../../../../../../mnt/nfs03-R6/BRACS/BRACS_WSI/train/Group_AT/Type_ADH: 28 files
../../../../../../../../mnt/nfs03-R6/BRACS/BRACS_WSI/train/Group_BT/Type_N: 27 files
../../../../../../../../mnt/nfs03-R6/BRACS/BRACS_WSI/train/Group_BT/Type_PB: 120 files
../../../../../../../../mnt/nfs03-R6/BRACS/BRACS_WSI/train/Group_BT/Type_UDH: 56 files (error with: 1791)
../../../../../../../../mnt/nfs03-R6/BRACS/BRACS_WSI/val/Group_MT/Type_DCIS: 9 files
../../../../../../../../mnt/nfs03-R6/BRACS/BRACS_WSI/val/Group_MT/Type_IC: 12 files
../../../../../../../../mnt/nfs03-R6/BRACS/BRACS_WSI/val/Group_AT/Type_FEA: 6 files
../../../../../../../../mnt/nfs03-R6/BRACS/BRACS_WSI/val/Group_AT/Type_ADH: 8 files
../../../../../../../../mnt/nfs03-R6/BRACS/BRACS_WSI/val/Group_BT/Type_N: 10 files
../../../../../../../../mnt/nfs03-R6/BRACS/BRACS_WSI/val/Group_BT/Type_PB: 11 files
../../../../../../../../mnt/nfs03-R6/BRACS/BRACS_WSI/val/Group_BT/Type_UDH: 9 files
../../../../../../../../mnt/nfs03-R6/BRACS/BRACS_WSI/test/Group_MT/Type_DCIS: 12 files
../../../../../../../../mnt/nfs03-R6/BRACS/BRACS_WSI/test/Group_MT/Type_IC: 20 files
../../../../../../../../mnt/nfs03-R6/BRACS/BRACS_WSI/test/Group_AT/Type_FEA: 11 files
../../../../../../../../mnt/nfs03-R6/BRACS/BRACS_WSI/test/Group_AT/Type_ADH: 12 files
../../../../../../../../mnt/nfs03-R6/BRACS/BRACS_WSI/test/Group_BT/Type_N: 7 files
../../../../../../../../mnt/nfs03-R6/BRACS/BRACS_WSI/test/Group_BT/Type_PB: 16 files
../../../../../../../../mnt/nfs03-R6/BRACS/BRACS_WSI/test/Group_BT/Type_UDH: 9 files